Updates for 6.2
oinanoanalysis/h5oina pull request #11
Opened 2024-12-18 14:41 UTC by k8macarthur

2024-12-20 09:33 UTC, ppinard requested changes

2024-12-20 09:33 UTC, ppinard commented on H5OINAFile.md
> -Beam Position X | | H5T_NATIVE_FLOAT | (size, 1) | X position of the beam in the real-world (in micrometers). The origin is in the center of the image, and a mathematical X axis that is positive when
Why is this changed?

2024-12-20 09:33 UTC, ppinard commented on H5OINAFile.md
> -Apparent Concentration | | Contains one dataset for each element analysed (e.g. Al). Each value (stored as H5T_NATIVE_FLOAT) corresponds to the first estimate of the concentration of an element befor
We lost the "Only available for Feature data". I think this still applies

2025-01-07 14:28 UTC, k8macarthur commented on H5OINAFile.md
> -Beam Position X | | H5T_NATIVE_FLOAT | (size, 1) | X position of the beam in the real-world (in micrometers). The origin is in the center of the image, and a mathematical X axis that is positive when
Must be a copying issue. I've reverted this change.

2025-01-07 14:28 UTC, k8macarthur commented on H5OINAFile.md
> -Apparent Concentration | | Contains one dataset for each element analysed (e.g. Al). Each value (stored as H5T_NATIVE_FLOAT) corresponds to the first estimate of the concentration of an element befor
Ah, yes that should probably remain for the last 3 points. Fixed.

2025-01-07 22:21 UTC, ppinard approved these changes

2025-01-07 22:21 UTC, merged